version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # root账号密码
    ports:
      - "127.0.0.1:4306:3306"
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      my_network:
        aliases:
          - mysql_db_container_hostname
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 9080:8080
    networks:
      my_network:
  nuxt_app_container:
    container_name: nuxt56_app
    restart: always
    #构建容器
    build:
      context: .
      # 自动输入Y防止造成编译卡死
      args:
        - "-y"
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql_db_container_hostname:3306/ycxt
      NUXT_BASE_URL: https://jsonplaceholder.typicode.com
      JSON_SECRET: thisisjsonsecret
    #command: >
    #  /bin/sh -c 'npm run clear npm run migrate && npm run build && npm start npm run clear && '
    command: >
     /bin/sh -c ' npm run migratePro && npm run build && npm start'
    depends_on:
      mysql_db_container:
        condition: service_healthy
    networks:
      my_network:
volumes:
  mysql_db_data_container:
networks:
  my_network:
